/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { MiscController } from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('MiscController', () => {
  let controller : MiscController;

  beforeAll(() => {
    controller = new MiscController(testClient);
  });

  it('should Root', async () => {
    const xAmzContentSha256 = 'UNSIGNED-PAYLOAD';

    const response = await makeApiCall(
      () => controller.root(xAmzContentSha256)
    );

    expect(response.statusCode).toBe(200);
  });
});
