/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { PublicAccessBlockController } from '../src';
import { testClient } from './testClient.js';
import { makeApiCall } from './testHelper.js';

describe('PublicAccessBlockController', () => {
  let controller : PublicAccessBlockController;

  beforeAll(() => {
    controller = new PublicAccessBlockController(testClient);
  });

  it('should Public Access Block', async () => {
    const publicAccessBlock = '';

    const xAmzContentSha256 = 'UNSIGNED-PAYLOAD';

    const response = await makeApiCall(
      () => controller.publicAccessBlock(publicAccessBlock, xAmzContentSha256)
    );

    expect(response.statusCode).toBe(200);
  });

  it('should Public Access Block1', async () => {
    const publicAccessBlock = '';

    const xAmzContentSha256 = 'UNSIGNED-PAYLOAD';

    const response = await makeApiCall(
      () => controller.publicAccessBlock1(publicAccessBlock, xAmzContentSha256)
    );

    expect(response.statusCode).toBe(200);
  });
});
