/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';

/**
 * Creates an instance of Custom
 */
interface Custom {
  Code: string;
  Message: string;
  BucketName: string;
  RequestId: string;
  HostId: string;
}

export class CustomError extends ApiError<Custom> {}
