/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for ErrorException type.
 */
public class ErrorException extends ApiException {
    private static final long serialVersionUID = -6312778554938503569L;
    private String code;
    private String message;
    private String bucketName;
    private String requestId;
    private String hostId;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public ErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Code.
     * @return Returns the String
     */
    @JsonGetter("Code")
    @XmlElement(name = "Code")
    public String getCode() {
        return this.code;
    }

    /**
     * Setter for Code.
     * @param code Value for String
     */
    @JsonSetter("Code")
    private void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("Message")
    @XmlElement(name = "Message")
    public String getMessageField() {
        return this.message;
    }

    /**
     * Setter for Message.
     * @param messageField Value for String
     */
    @JsonSetter("Message")
    private void setMessageField(String messageField) {
        this.message = messageField;
    }

    /**
     * Getter for BucketName.
     * @return Returns the String
     */
    @JsonGetter("BucketName")
    @XmlElement(name = "BucketName")
    public String getBucketName() {
        return this.bucketName;
    }

    /**
     * Setter for BucketName.
     * @param bucketName Value for String
     */
    @JsonSetter("BucketName")
    private void setBucketName(String bucketName) {
        this.bucketName = bucketName;
    }

    /**
     * Getter for RequestId.
     * @return Returns the String
     */
    @JsonGetter("RequestId")
    @XmlElement(name = "RequestId")
    public String getRequestId() {
        return this.requestId;
    }

    /**
     * Setter for RequestId.
     * @param requestId Value for String
     */
    @JsonSetter("RequestId")
    private void setRequestId(String requestId) {
        this.requestId = requestId;
    }

    /**
     * Getter for HostId.
     * @return Returns the String
     */
    @JsonGetter("HostId")
    @XmlElement(name = "HostId")
    public String getHostId() {
        return this.hostId;
    }

    /**
     * Setter for HostId.
     * @param hostId Value for String
     */
    @JsonSetter("HostId")
    private void setHostId(String hostId) {
        this.hostId = hostId;
    }

    /**
     * Converts this ErrorException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ErrorException [" + "statusCode=" + getResponseCode() + ", message=" + getMessage()
                + ", code=" + code + ", message=" + message + ", bucketName=" + bucketName
                + ", requestId=" + requestId + ", hostId=" + hostId + "]";
    }
}
