/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.controllers;

import com.amazonaws.s3.ApiHelper;
import com.amazonaws.s3.Server;
import com.amazonaws.s3.exceptions.ApiException;
import com.amazonaws.s3.http.request.HttpMethod;
import com.amazonaws.s3.models.DynamicResponse;
import com.amazonaws.s3.models.ListBucketResult;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import javax.xml.bind.JAXBException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class AccelerateController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public AccelerateController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a
     * bucket-level feature that enables you to perform faster data transfers to Amazon S3.
     * @param  accelerate  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public DynamicResponse bucketAccelerateConfiguration(
            final String accelerate,
            final String body,
            final String bucket) throws ApiException, IOException {
        return prepareBucketAccelerateConfigurationRequest(accelerate, body, bucket).execute();
    }

    /**
     * Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a
     * bucket-level feature that enables you to perform faster data transfers to Amazon S3.
     * @param  accelerate  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     */
    public CompletableFuture<DynamicResponse> bucketAccelerateConfigurationAsync(
            final String accelerate,
            final String body,
            final String bucket) {
        try {
            return prepareBucketAccelerateConfigurationRequest(accelerate, body, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketAccelerateConfiguration.
     */
    private ApiCall<DynamicResponse, ApiException> prepareBucketAccelerateConfigurationRequest(
            final String accelerate,
            final String body,
            final String bucket) {
        return new ApiCall.Builder<DynamicResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .bodyParam(param -> param.value(body))
                        .queryParam(param -> param.key("accelerate")
                                .value(accelerate))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.DYNAMIC_RESPONSE)
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a
     * bucket-level feature that enables you to perform faster data transfers to Amazon S3.
     * @param  accelerate  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the ListBucketResult response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     * @throws    JAXBException    Signals that a JAXB exception occurred.
     */
    public ListBucketResult bucketAccelerateConfiguration1(
            final String accelerate,
            final String bucket) throws ApiException, IOException, JAXBException {
        return prepareBucketAccelerateConfiguration1Request(accelerate, bucket).execute();
    }

    /**
     * Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a
     * bucket-level feature that enables you to perform faster data transfers to Amazon S3.
     * @param  accelerate  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the ListBucketResult response from the API call
     */
    public CompletableFuture<ListBucketResult> bucketAccelerateConfiguration1Async(
            final String accelerate,
            final String bucket) {
        try {
            return prepareBucketAccelerateConfiguration1Request(accelerate, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketAccelerateConfiguration1.
     */
    private ApiCall<ListBucketResult, ApiException> prepareBucketAccelerateConfiguration1Request(
            final String accelerate,
            final String bucket) {
        return new ApiCall.Builder<ListBucketResult, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("accelerate")
                                .value(accelerate))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/xml"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserializeXml(response,
                                        ListBucketResult.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This implementation of the GET operation uses the accelerate subresource to return the
     * Transfer Acceleration state of a bucket, which is either Enabled or Suspended. Amazon S3
     * Transfer Acceleration is a bucket-level feature that enables you to perform faster data
     * transfers to and from Amazon S3.
     * @param  accelerate  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void getBucketAccelerateConfiguration(
            final String accelerate,
            final String xAmzContentSha256,
            final String bucket) throws ApiException, IOException {
        prepareGetBucketAccelerateConfigurationRequest(accelerate, xAmzContentSha256,
                bucket).execute();
    }

    /**
     * This implementation of the GET operation uses the accelerate subresource to return the
     * Transfer Acceleration state of a bucket, which is either Enabled or Suspended. Amazon S3
     * Transfer Acceleration is a bucket-level feature that enables you to perform faster data
     * transfers to and from Amazon S3.
     * @param  accelerate  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> getBucketAccelerateConfigurationAsync(
            final String accelerate,
            final String xAmzContentSha256,
            final String bucket) {
        try {
            return prepareGetBucketAccelerateConfigurationRequest(accelerate, xAmzContentSha256,
            bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for getBucketAccelerateConfiguration.
     */
    private ApiCall<Void, ApiException> prepareGetBucketAccelerateConfigurationRequest(
            final String accelerate,
            final String xAmzContentSha256,
            final String bucket) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("accelerate")
                                .value(accelerate))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}