/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.controllers;

import com.amazonaws.s3.ApiHelper;
import com.amazonaws.s3.Server;
import com.amazonaws.s3.exceptions.ApiException;
import com.amazonaws.s3.http.request.HttpMethod;
import com.amazonaws.s3.models.DynamicResponse;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class AnalyticsController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public AnalyticsController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * This implementation of the GET operation returns an analytics configuration (identified by
     * the analytics configuration ID) from the bucket.
     * @param  analytics  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String bucketAnalytics(
            final String analytics,
            final String xAmzContentSha256,
            final String bucket) throws ApiException, IOException {
        return prepareBucketAnalyticsRequest(analytics, xAmzContentSha256, bucket).execute();
    }

    /**
     * This implementation of the GET operation returns an analytics configuration (identified by
     * the analytics configuration ID) from the bucket.
     * @param  analytics  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> bucketAnalyticsAsync(
            final String analytics,
            final String xAmzContentSha256,
            final String bucket) {
        try {
            return prepareBucketAnalyticsRequest(analytics, xAmzContentSha256, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketAnalytics.
     */
    private ApiCall<String, ApiException> prepareBucketAnalyticsRequest(
            final String analytics,
            final String xAmzContentSha256,
            final String bucket) {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("analytics")
                                .value(analytics))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Lists the analytics configurations for the bucket. You can have up to 1,000 analytics
     * configurations per bucket.
     * @param  analytics  Required parameter:
     * @param  id  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String bucketAnalyticsConfigurations(
            final String analytics,
            final String id,
            final String xAmzContentSha256,
            final String bucket) throws ApiException, IOException {
        return prepareBucketAnalyticsConfigurationsRequest(analytics, id, xAmzContentSha256,
                bucket).execute();
    }

    /**
     * Lists the analytics configurations for the bucket. You can have up to 1,000 analytics
     * configurations per bucket.
     * @param  analytics  Required parameter:
     * @param  id  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> bucketAnalyticsConfigurationsAsync(
            final String analytics,
            final String id,
            final String xAmzContentSha256,
            final String bucket) {
        try {
            return prepareBucketAnalyticsConfigurationsRequest(analytics, id, xAmzContentSha256,
            bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketAnalyticsConfigurations.
     */
    private ApiCall<String, ApiException> prepareBucketAnalyticsConfigurationsRequest(
            final String analytics,
            final String id,
            final String xAmzContentSha256,
            final String bucket) {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("analytics")
                                .value(analytics))
                        .queryParam(param -> param.key("id")
                                .value(id))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Sets an analytics configuration for the bucket (specified by the analytics configuration ID).
     * You can have up to 1,000 analytics configurations per bucket.
     * @param  analytics  Required parameter:
     * @param  id  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void bucketAnalyticsConfigurations1(
            final String analytics,
            final String id,
            final String body,
            final String bucket) throws ApiException, IOException {
        prepareBucketAnalyticsConfigurations1Request(analytics, id, body, bucket).execute();
    }

    /**
     * Sets an analytics configuration for the bucket (specified by the analytics configuration ID).
     * You can have up to 1,000 analytics configurations per bucket.
     * @param  analytics  Required parameter:
     * @param  id  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> bucketAnalyticsConfigurations1Async(
            final String analytics,
            final String id,
            final String body,
            final String bucket) {
        try {
            return prepareBucketAnalyticsConfigurations1Request(analytics, id, body, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketAnalyticsConfigurations1.
     */
    private ApiCall<Void, ApiException> prepareBucketAnalyticsConfigurations1Request(
            final String analytics,
            final String id,
            final String body,
            final String bucket) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .bodyParam(param -> param.value(body))
                        .queryParam(param -> param.key("analytics")
                                .value(analytics))
                        .queryParam(param -> param.key("Id")
                                .value(id))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Deletes an analytics configuration for the bucket (specified by the analytics configuration
     * ID).
     * @param  analytics  Required parameter:
     * @param  id  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public DynamicResponse deleteBucketAnalyticsConfiguration(
            final String analytics,
            final String id,
            final String body,
            final String bucket) throws ApiException, IOException {
        return prepareDeleteBucketAnalyticsConfigurationRequest(analytics, id, body,
                bucket).execute();
    }

    /**
     * Deletes an analytics configuration for the bucket (specified by the analytics configuration
     * ID).
     * @param  analytics  Required parameter:
     * @param  id  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     */
    public CompletableFuture<DynamicResponse> deleteBucketAnalyticsConfigurationAsync(
            final String analytics,
            final String id,
            final String body,
            final String bucket) {
        try {
            return prepareDeleteBucketAnalyticsConfigurationRequest(analytics, id, body,
            bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deleteBucketAnalyticsConfiguration.
     */
    private ApiCall<DynamicResponse, ApiException> prepareDeleteBucketAnalyticsConfigurationRequest(
            final String analytics,
            final String id,
            final String body,
            final String bucket) {
        return new ApiCall.Builder<DynamicResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .bodyParam(param -> param.value(body))
                        .queryParam(param -> param.key("analytics")
                                .value(analytics))
                        .queryParam(param -> param.key("id")
                                .value(id))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.DYNAMIC_RESPONSE)
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}