/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.controllers;

import com.amazonaws.s3.ApiHelper;
import com.amazonaws.s3.Server;
import com.amazonaws.s3.exceptions.ApiException;
import com.amazonaws.s3.http.request.HttpMethod;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class InventoryController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public InventoryController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Returns an inventory configuration (identified by the inventory configuration ID) from the
     * bucket.
     * @param  inventory  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String bucketInventoryConfiguration(
            final String inventory,
            final String xAmzContentSha256,
            final String bucket) throws ApiException, IOException {
        return prepareBucketInventoryConfigurationRequest(inventory, xAmzContentSha256,
                bucket).execute();
    }

    /**
     * Returns an inventory configuration (identified by the inventory configuration ID) from the
     * bucket.
     * @param  inventory  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> bucketInventoryConfigurationAsync(
            final String inventory,
            final String xAmzContentSha256,
            final String bucket) {
        try {
            return prepareBucketInventoryConfigurationRequest(inventory, xAmzContentSha256,
            bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketInventoryConfiguration.
     */
    private ApiCall<String, ApiException> prepareBucketInventoryConfigurationRequest(
            final String inventory,
            final String xAmzContentSha256,
            final String bucket) {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("inventory")
                                .value(inventory))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Deletes an inventory configuration (identified by the inventory ID) from the bucket.
     * @param  inventory  Required parameter:
     * @param  id  Required parameter:
     * @param  bucket  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void deleteBucketInventoryConfiguration(
            final String inventory,
            final String id,
            final String bucket) throws ApiException, IOException {
        prepareDeleteBucketInventoryConfigurationRequest(inventory, id, bucket).execute();
    }

    /**
     * Deletes an inventory configuration (identified by the inventory ID) from the bucket.
     * @param  inventory  Required parameter:
     * @param  id  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> deleteBucketInventoryConfigurationAsync(
            final String inventory,
            final String id,
            final String bucket) {
        try {
            return prepareDeleteBucketInventoryConfigurationRequest(inventory, id, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deleteBucketInventoryConfiguration.
     */
    private ApiCall<Void, ApiException> prepareDeleteBucketInventoryConfigurationRequest(
            final String inventory,
            final String id,
            final String bucket) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("inventory")
                                .value(inventory))
                        .queryParam(param -> param.key("Id")
                                .value(id))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * This implementation of the PUT operation adds an inventory configuration (identified by the
     * inventory ID) to the bucket. You can have up to 1,000 inventory configurations per bucket.
     * @param  inventory  Required parameter:
     * @param  id  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void bucketInventoryConfiguration1(
            final String inventory,
            final String id,
            final String body,
            final String bucket) throws ApiException, IOException {
        prepareBucketInventoryConfiguration1Request(inventory, id, body, bucket).execute();
    }

    /**
     * This implementation of the PUT operation adds an inventory configuration (identified by the
     * inventory ID) to the bucket. You can have up to 1,000 inventory configurations per bucket.
     * @param  inventory  Required parameter:
     * @param  id  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> bucketInventoryConfiguration1Async(
            final String inventory,
            final String id,
            final String body,
            final String bucket) {
        try {
            return prepareBucketInventoryConfiguration1Request(inventory, id, body, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketInventoryConfiguration1.
     */
    private ApiCall<Void, ApiException> prepareBucketInventoryConfiguration1Request(
            final String inventory,
            final String id,
            final String body,
            final String bucket) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .bodyParam(param -> param.value(body))
                        .queryParam(param -> param.key("inventory")
                                .value(inventory))
                        .queryParam(param -> param.key("Id")
                                .value(id))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}