/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.controllers;

import com.amazonaws.s3.ApiHelper;
import com.amazonaws.s3.Server;
import com.amazonaws.s3.exceptions.ApiException;
import com.amazonaws.s3.http.request.HttpMethod;
import com.amazonaws.s3.models.ListAllMyBucketsResult;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;
import javax.xml.bind.JAXBException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class LockController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public LockController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Gets the Object Lock configuration for a bucket. The rule specified in the Object Lock
     * configuration will be applied by default to every new object placed in the specified bucket.
     * For more information, see Locking Objects.
     * @param  objectLock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @return    Returns the ListAllMyBucketsResult response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     * @throws    JAXBException    Signals that a JAXB exception occurred.
     */
    public ListAllMyBucketsResult objectLockConfiguration(
            final String objectLock,
            final String xAmzContentSha256) throws ApiException, IOException, JAXBException {
        return prepareObjectLockConfigurationRequest(objectLock, xAmzContentSha256).execute();
    }

    /**
     * Gets the Object Lock configuration for a bucket. The rule specified in the Object Lock
     * configuration will be applied by default to every new object placed in the specified bucket.
     * For more information, see Locking Objects.
     * @param  objectLock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @return    Returns the ListAllMyBucketsResult response from the API call
     */
    public CompletableFuture<ListAllMyBucketsResult> objectLockConfigurationAsync(
            final String objectLock,
            final String xAmzContentSha256) {
        try {
            return prepareObjectLockConfigurationRequest(objectLock, xAmzContentSha256).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for objectLockConfiguration.
     */
    private ApiCall<ListAllMyBucketsResult, ApiException> prepareObjectLockConfigurationRequest(
            final String objectLock,
            final String xAmzContentSha256) {
        return new ApiCall.Builder<ListAllMyBucketsResult, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/")
                        .queryParam(param -> param.key("object-lock")
                                .value(objectLock))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/xml"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserializeXml(response,
                                        ListAllMyBucketsResult.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Gets the Object Lock configuration for a bucket. The rule specified in the Object Lock
     * configuration will be applied by default to every new object placed in the specified bucket.
     * For more information, see Locking Objects.
     * @param  objectLock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @return    Returns the ListAllMyBucketsResult response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     * @throws    JAXBException    Signals that a JAXB exception occurred.
     */
    public ListAllMyBucketsResult objectLockConfigurationCopy(
            final String objectLock,
            final String xAmzContentSha256) throws ApiException, IOException, JAXBException {
        return prepareObjectLockConfigurationCopyRequest(objectLock, xAmzContentSha256).execute();
    }

    /**
     * Gets the Object Lock configuration for a bucket. The rule specified in the Object Lock
     * configuration will be applied by default to every new object placed in the specified bucket.
     * For more information, see Locking Objects.
     * @param  objectLock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @return    Returns the ListAllMyBucketsResult response from the API call
     */
    public CompletableFuture<ListAllMyBucketsResult> objectLockConfigurationCopyAsync(
            final String objectLock,
            final String xAmzContentSha256) {
        try {
            return prepareObjectLockConfigurationCopyRequest(objectLock, xAmzContentSha256).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for objectLockConfigurationCopy.
     */
    private ApiCall<ListAllMyBucketsResult, ApiException> prepareObjectLockConfigurationCopyRequest(
            final String objectLock,
            final String xAmzContentSha256) {
        return new ApiCall.Builder<ListAllMyBucketsResult, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/")
                        .queryParam(param -> param.key("object-lock")
                                .value(objectLock))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/xml"))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserializeXml(response,
                                        ListAllMyBucketsResult.class))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}