/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.controllers;

import com.amazonaws.s3.ApiHelper;
import com.amazonaws.s3.Server;
import com.amazonaws.s3.exceptions.ApiException;
import com.amazonaws.s3.http.request.HttpMethod;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class PublicAccessBlockController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public PublicAccessBlockController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Retrieves the PublicAccessBlock configuration for an Amazon S3 bucket. In order to use this
     * operation, you must have the s3:GetBucketPublicAccessBlock permission. For more information
     * about Amazon S3 permissions, see Specifying Permissions in a Policy.
     * @param  publicAccessBlock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void publicAccessBlock(
            final String publicAccessBlock,
            final String xAmzContentSha256) throws ApiException, IOException {
        preparePublicAccessBlockRequest(publicAccessBlock, xAmzContentSha256).execute();
    }

    /**
     * Retrieves the PublicAccessBlock configuration for an Amazon S3 bucket. In order to use this
     * operation, you must have the s3:GetBucketPublicAccessBlock permission. For more information
     * about Amazon S3 permissions, see Specifying Permissions in a Policy.
     * @param  publicAccessBlock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> publicAccessBlockAsync(
            final String publicAccessBlock,
            final String xAmzContentSha256) {
        try {
            return preparePublicAccessBlockRequest(publicAccessBlock, xAmzContentSha256).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for publicAccessBlock.
     */
    private ApiCall<Void, ApiException> preparePublicAccessBlockRequest(
            final String publicAccessBlock,
            final String xAmzContentSha256) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/")
                        .queryParam(param -> param.key("publicAccessBlock")
                                .value(publicAccessBlock))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Retrieves the PublicAccessBlock configuration for an Amazon S3 bucket. In order to use this
     * operation, you must have the s3:GetBucketPublicAccessBlock permission. For more information
     * about Amazon S3 permissions, see Specifying Permissions in a Policy.
     * @param  publicAccessBlock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void publicAccessBlock1(
            final String publicAccessBlock,
            final String xAmzContentSha256) throws ApiException, IOException {
        preparePublicAccessBlock1Request(publicAccessBlock, xAmzContentSha256).execute();
    }

    /**
     * Retrieves the PublicAccessBlock configuration for an Amazon S3 bucket. In order to use this
     * operation, you must have the s3:GetBucketPublicAccessBlock permission. For more information
     * about Amazon S3 permissions, see Specifying Permissions in a Policy.
     * @param  publicAccessBlock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> publicAccessBlock1Async(
            final String publicAccessBlock,
            final String xAmzContentSha256) {
        try {
            return preparePublicAccessBlock1Request(publicAccessBlock, xAmzContentSha256).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for publicAccessBlock1.
     */
    private ApiCall<Void, ApiException> preparePublicAccessBlock1Request(
            final String publicAccessBlock,
            final String xAmzContentSha256) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/")
                        .queryParam(param -> param.key("publicAccessBlock")
                                .value(publicAccessBlock))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Removes the PublicAccessBlock configuration for an Amazon S3 bucket. In order to use this
     * operation, you must have the s3:PutBucketPublicAccessBlock permission.
     * @param  publicAccessBlock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void publicAccessBlock2(
            final String publicAccessBlock,
            final String xAmzContentSha256,
            final String bucket) throws ApiException, IOException {
        preparePublicAccessBlock2Request(publicAccessBlock, xAmzContentSha256, bucket).execute();
    }

    /**
     * Removes the PublicAccessBlock configuration for an Amazon S3 bucket. In order to use this
     * operation, you must have the s3:PutBucketPublicAccessBlock permission.
     * @param  publicAccessBlock  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> publicAccessBlock2Async(
            final String publicAccessBlock,
            final String xAmzContentSha256,
            final String bucket) {
        try {
            return preparePublicAccessBlock2Request(publicAccessBlock, xAmzContentSha256,
            bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for publicAccessBlock2.
     */
    private ApiCall<Void, ApiException> preparePublicAccessBlock2Request(
            final String publicAccessBlock,
            final String xAmzContentSha256,
            final String bucket) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("publicAccessBlock")
                                .value(publicAccessBlock))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}