/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.controllers;

import com.amazonaws.s3.ApiHelper;
import com.amazonaws.s3.Server;
import com.amazonaws.s3.exceptions.ApiException;
import com.amazonaws.s3.exceptions.ErrorException;
import com.amazonaws.s3.http.request.HttpMethod;
import com.amazonaws.s3.models.DynamicResponse;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class ReplicationController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public ReplicationController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Returns the replication configuration of a bucket.
     * @param  replication  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void bucketReplication(
            final String replication,
            final String xAmzContentSha256,
            final String bucket) throws ApiException, IOException {
        prepareBucketReplicationRequest(replication, xAmzContentSha256, bucket).execute();
    }

    /**
     * Returns the replication configuration of a bucket.
     * @param  replication  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> bucketReplicationAsync(
            final String replication,
            final String xAmzContentSha256,
            final String bucket) {
        try {
            return prepareBucketReplicationRequest(replication, xAmzContentSha256, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketReplication.
     */
    private ApiCall<Void, ApiException> prepareBucketReplicationRequest(
            final String replication,
            final String xAmzContentSha256,
            final String bucket) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("replication")
                                .value(replication))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .localErrorCase("404",
                                 ErrorCase.setReason("Not Found",
                                (reason, context) -> new ErrorException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Creates a replication configuration or replaces an existing one.
     * @param  replication  Required parameter:
     * @param  contentMD5  Required parameter:
     * @param  xAmzBucketObjectLockToken  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void bucketReplication1(
            final String replication,
            final String contentMD5,
            final String xAmzBucketObjectLockToken,
            final String body,
            final String bucket) throws ApiException, IOException {
        prepareBucketReplication1Request(replication, contentMD5, xAmzBucketObjectLockToken, body,
                bucket).execute();
    }

    /**
     * Creates a replication configuration or replaces an existing one.
     * @param  replication  Required parameter:
     * @param  contentMD5  Required parameter:
     * @param  xAmzBucketObjectLockToken  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> bucketReplication1Async(
            final String replication,
            final String contentMD5,
            final String xAmzBucketObjectLockToken,
            final String body,
            final String bucket) {
        try {
            return prepareBucketReplication1Request(replication, contentMD5, xAmzBucketObjectLockToken,
            body, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketReplication1.
     */
    private ApiCall<Void, ApiException> prepareBucketReplication1Request(
            final String replication,
            final String contentMD5,
            final String xAmzBucketObjectLockToken,
            final String body,
            final String bucket) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .bodyParam(param -> param.value(body))
                        .queryParam(param -> param.key("replication")
                                .value(replication))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-MD5")
                                .value(contentMD5).isRequired(false))
                        .headerParam(param -> param.key("x-amz-bucket-object-lock-token")
                                .value(xAmzBucketObjectLockToken).isRequired(false))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Deletes the replication configuration from the bucket.
     * @param  replication  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public DynamicResponse deleteBucketReplication(
            final String replication,
            final String bucket) throws ApiException, IOException {
        return prepareDeleteBucketReplicationRequest(replication, bucket).execute();
    }

    /**
     * Deletes the replication configuration from the bucket.
     * @param  replication  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     */
    public CompletableFuture<DynamicResponse> deleteBucketReplicationAsync(
            final String replication,
            final String bucket) {
        try {
            return prepareDeleteBucketReplicationRequest(replication, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deleteBucketReplication.
     */
    private ApiCall<DynamicResponse, ApiException> prepareDeleteBucketReplicationRequest(
            final String replication,
            final String bucket) {
        return new ApiCall.Builder<DynamicResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("replication")
                                .value(replication))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.DYNAMIC_RESPONSE)
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}