/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.controllers;

import com.amazonaws.s3.ApiHelper;
import com.amazonaws.s3.Server;
import com.amazonaws.s3.exceptions.ApiException;
import com.amazonaws.s3.http.request.HttpMethod;
import com.amazonaws.s3.models.DynamicResponse;
import io.apimatic.core.ApiCall;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class TaggingController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public TaggingController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Returns the tag set associated with the bucket.
     * @param  tagging  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public void bucketTagging(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket) throws ApiException, IOException {
        prepareBucketTaggingRequest(tagging, xAmzContentSha256, bucket).execute();
    }

    /**
     * Returns the tag set associated with the bucket.
     * @param  tagging  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the void response from the API call
     */
    public CompletableFuture<Void> bucketTaggingAsync(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket) {
        try {
            return prepareBucketTaggingRequest(tagging, xAmzContentSha256, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketTagging.
     */
    private ApiCall<Void, ApiException> prepareBucketTaggingRequest(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket) {
        return new ApiCall.Builder<Void, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("tagging")
                                .value(tagging))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Sets the tags for a bucket.
     * @param  tagging  Required parameter:
     * @param  contentMD5  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public DynamicResponse bucketTagging1(
            final String tagging,
            final String contentMD5,
            final String body,
            final String bucket) throws ApiException, IOException {
        return prepareBucketTagging1Request(tagging, contentMD5, body, bucket).execute();
    }

    /**
     * Sets the tags for a bucket.
     * @param  tagging  Required parameter:
     * @param  contentMD5  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     */
    public CompletableFuture<DynamicResponse> bucketTagging1Async(
            final String tagging,
            final String contentMD5,
            final String body,
            final String bucket) {
        try {
            return prepareBucketTagging1Request(tagging, contentMD5, body, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for bucketTagging1.
     */
    private ApiCall<DynamicResponse, ApiException> prepareBucketTagging1Request(
            final String tagging,
            final String contentMD5,
            final String body,
            final String bucket) {
        return new ApiCall.Builder<DynamicResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .bodyParam(param -> param.value(body))
                        .queryParam(param -> param.key("tagging")
                                .value(tagging))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("Content-MD5")
                                .value(contentMD5).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.DYNAMIC_RESPONSE)
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Deletes the tags from the bucket.
     * @param  tagging  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public DynamicResponse deleteBucketTagging(
            final String tagging,
            final String bucket) throws ApiException, IOException {
        return prepareDeleteBucketTaggingRequest(tagging, bucket).execute();
    }

    /**
     * Deletes the tags from the bucket.
     * @param  tagging  Required parameter:
     * @param  bucket  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     */
    public CompletableFuture<DynamicResponse> deleteBucketTaggingAsync(
            final String tagging,
            final String bucket) {
        try {
            return prepareDeleteBucketTaggingRequest(tagging, bucket).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deleteBucketTagging.
     */
    private ApiCall<DynamicResponse, ApiException> prepareDeleteBucketTaggingRequest(
            final String tagging,
            final String bucket) {
        return new ApiCall.Builder<DynamicResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}")
                        .queryParam(param -> param.key("tagging")
                                .value(tagging))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.DYNAMIC_RESPONSE)
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Returns the tag-set of an object. You send the GET request against the tagging subresource
     * associated with the object.
     * @param  tagging  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @param  key  Required parameter:
     * @return    Returns the String response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public String objectTagging(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket,
            final String key) throws ApiException, IOException {
        return prepareObjectTaggingRequest(tagging, xAmzContentSha256, bucket, key).execute();
    }

    /**
     * Returns the tag-set of an object. You send the GET request against the tagging subresource
     * associated with the object.
     * @param  tagging  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @param  key  Required parameter:
     * @return    Returns the String response from the API call
     */
    public CompletableFuture<String> objectTaggingAsync(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket,
            final String key) {
        try {
            return prepareObjectTaggingRequest(tagging, xAmzContentSha256, bucket, key).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for objectTagging.
     */
    private ApiCall<String, ApiException> prepareObjectTaggingRequest(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket,
            final String key) {
        return new ApiCall.Builder<String, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}/{key}")
                        .queryParam(param -> param.key("tagging")
                                .value(tagging))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .templateParam(param -> param.key("key").value(key)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> new String(response))
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Returns the tag-set of an object. You send the GET request against the tagging subresource
     * associated with the object.
     * @param  tagging  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @param  key  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public DynamicResponse tagging(
            final String tagging,
            final String body,
            final String bucket,
            final String key) throws ApiException, IOException {
        return prepareTaggingRequest(tagging, body, bucket, key).execute();
    }

    /**
     * Returns the tag-set of an object. You send the GET request against the tagging subresource
     * associated with the object.
     * @param  tagging  Required parameter:
     * @param  body  Required parameter:
     * @param  bucket  Required parameter:
     * @param  key  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     */
    public CompletableFuture<DynamicResponse> taggingAsync(
            final String tagging,
            final String body,
            final String bucket,
            final String key) {
        try {
            return prepareTaggingRequest(tagging, body, bucket, key).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for tagging.
     */
    private ApiCall<DynamicResponse, ApiException> prepareTaggingRequest(
            final String tagging,
            final String body,
            final String bucket,
            final String key) {
        return new ApiCall.Builder<DynamicResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}/{key}")
                        .bodyParam(param -> param.value(body))
                        .queryParam(param -> param.key("tagging")
                                .value(tagging))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .templateParam(param -> param.key("key").value(key)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.DYNAMIC_RESPONSE)
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * Removes the entire tag set from the specified object. For more information about managing
     * object tags, see Object Tagging.
     * @param  tagging  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @param  key  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public DynamicResponse deleteObjectTagging(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket,
            final String key) throws ApiException, IOException {
        return prepareDeleteObjectTaggingRequest(tagging, xAmzContentSha256, bucket, key).execute();
    }

    /**
     * Removes the entire tag set from the specified object. For more information about managing
     * object tags, see Object Tagging.
     * @param  tagging  Required parameter:
     * @param  xAmzContentSha256  Required parameter:
     * @param  bucket  Required parameter:
     * @param  key  Required parameter:
     * @return    Returns the DynamicResponse response from the API call
     */
    public CompletableFuture<DynamicResponse> deleteObjectTaggingAsync(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket,
            final String key) {
        try {
            return prepareDeleteObjectTaggingRequest(tagging, xAmzContentSha256, bucket,
            key).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for deleteObjectTagging.
     */
    private ApiCall<DynamicResponse, ApiException> prepareDeleteObjectTaggingRequest(
            final String tagging,
            final String xAmzContentSha256,
            final String bucket,
            final String key) {
        return new ApiCall.Builder<DynamicResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.SERVER_1.value())
                        .path("/{bucket}/{key}")
                        .queryParam(param -> param.key("tagging")
                                .value(tagging))
                        .templateParam(param -> param.key("bucket").value(bucket)
                                .shouldEncode(true))
                        .templateParam(param -> param.key("key").value(key)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("x-amz-content-sha256")
                                .value(xAmzContentSha256).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .httpMethod(HttpMethod.DELETE))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.DYNAMIC_RESPONSE)
                        .nullify404(false)
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}