/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import com.amazonaws.s3.AWSS3Client;
import com.amazonaws.s3.exceptions.ApiException;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class PublicAccessBlockControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static AWSS3Client client;
    
    /**
     * Controller instance (for all tests).
     */
    private static PublicAccessBlockController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getPublicAccessBlockController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Retrieves the PublicAccessBlock configuration for an Amazon S3 bucket. In order to use this
     * operation, you must have the s3:GetBucketPublicAccessBlock permission. For more information
     * about Amazon S3 permissions, see Specifying Permissions in a Policy. .
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testPublicAccessBlock() throws Exception {
        // Parameters for the API call
        String publicAccessBlock = 
                "";
        String xAmzContentSha256 = 
                "UNSIGNED-PAYLOAD";

        // Set callback and perform API call
        try {
            controller.publicAccessBlock(publicAccessBlock, xAmzContentSha256);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

    /**
     * Retrieves the PublicAccessBlock configuration for an Amazon S3 bucket. In order to use this
     * operation, you must have the s3:GetBucketPublicAccessBlock permission. For more information
     * about Amazon S3 permissions, see Specifying Permissions in a Policy. .
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testPublicAccessBlock1() throws Exception {
        // Parameters for the API call
        String publicAccessBlock = 
                "";
        String xAmzContentSha256 = 
                "UNSIGNED-PAYLOAD";

        // Set callback and perform API call
        try {
            controller.publicAccessBlock1(publicAccessBlock, xAmzContentSha256);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

    }

}
