/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.utilities;

import io.apimatic.core.utilities.MapAdapter;

public class XmlMapAdapter extends MapAdapter {
    
}