/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ListBucketResult,
  listBucketResultSchema,
} from '../models/listBucketResult.js';
import { string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';

export class AccelerateController extends BaseController {
  /**
   * Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a bucket-
   * level feature that enables you to perform faster data transfers to Amazon S3.
   *
   * @param accelerate
   * @param body
   * @param bucket
   * @return Response from the API call
   */
  async bucketAccelerateConfiguration(
    accelerate: string,
    body: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      accelerate: [accelerate, string()],
      body: [body, string()],
      bucket: [bucket, string()],
    });
    req.query('accelerate', mapped.accelerate);
    req.text(mapped.body);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * Sets the accelerate configuration of an existing bucket. Amazon S3 Transfer Acceleration is a bucket-
   * level feature that enables you to perform faster data transfers to Amazon S3.
   *
   * @param accelerate
   * @param bucket
   * @return Response from the API call
   */
  async bucketAccelerateConfiguration1(
    accelerate: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListBucketResult>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      accelerate: [accelerate, string()],
      bucket: [bucket, string()],
    });
    req.query('accelerate', mapped.accelerate);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsXml(
      'ListBucketResult',
      listBucketResultSchema,
      requestOptions
    );
  }

  /**
   * This implementation of the GET operation uses the accelerate subresource to return the Transfer
   * Acceleration state of a bucket, which is either Enabled or Suspended. Amazon S3 Transfer
   * Acceleration is a bucket-level feature that enables you to perform faster data transfers to and from
   * Amazon S3.
   *
   * @param accelerate
   * @param xAmzContentSha256
   * @param bucket
   * @return Response from the API call
   */
  async getBucketAccelerateConfiguration(
    accelerate: string,
    xAmzContentSha256: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      accelerate: [accelerate, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('accelerate', mapped.accelerate);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.call(requestOptions);
  }
}
