/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';

export class AnalyticsController extends BaseController {
  /**
   * This implementation of the GET operation returns an analytics configuration (identified by the
   * analytics configuration ID) from the bucket.
   *
   * @param analytics
   * @param xAmzContentSha256
   * @param bucket
   * @return Response from the API call
   */
  async bucketAnalytics(
    analytics: string,
    xAmzContentSha256: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      analytics: [analytics, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('analytics', mapped.analytics);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsText(requestOptions);
  }

  /**
   * Lists the analytics configurations for the bucket. You can have up to 1,000 analytics configurations
   * per bucket.
   *
   * @param analytics
   * @param id
   * @param xAmzContentSha256
   * @param bucket
   * @return Response from the API call
   */
  async bucketAnalyticsConfigurations(
    analytics: string,
    id: string,
    xAmzContentSha256: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      analytics: [analytics, string()],
      id: [id, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('analytics', mapped.analytics);
    req.query('id', mapped.id);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsText(requestOptions);
  }

  /**
   * Sets an analytics configuration for the bucket (specified by the analytics configuration ID). You
   * can have up to 1,000 analytics configurations per bucket.
   *
   * @param analytics
   * @param id
   * @param body
   * @param bucket
   * @return Response from the API call
   */
  async bucketAnalyticsConfigurations1(
    analytics: string,
    id: string,
    body: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      analytics: [analytics, string()],
      id: [id, string()],
      body: [body, string()],
      bucket: [bucket, string()],
    });
    req.query('analytics', mapped.analytics);
    req.query('Id', mapped.id);
    req.text(mapped.body);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.call(requestOptions);
  }

  /**
   * Deletes an analytics configuration for the bucket (specified by the analytics configuration ID).
   *
   * @param analytics
   * @param id
   * @param body
   * @param bucket
   * @return Response from the API call
   */
  async deleteBucketAnalyticsConfiguration(
    analytics: string,
    id: string,
    body: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      analytics: [analytics, string()],
      id: [id, string()],
      body: [body, string()],
      bucket: [bucket, string()],
    });
    req.query('analytics', mapped.analytics);
    req.query('id', mapped.id);
    req.text(mapped.body);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsJson(unknown(), requestOptions);
  }
}
