/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';

export class CORSController extends BaseController {
  /**
   * Sets the cors configuration for your bucket. If the configuration exists, Amazon S3 replaces it.
   *
   * @param cors
   * @param contentMD5
   * @param body
   * @param bucket
   * @return Response from the API call
   */
  async cORS(
    cors: string,
    contentMD5: string,
    body: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      cors: [cors, string()],
      contentMD5: [contentMD5, string()],
      body: [body, string()],
      bucket: [bucket, string()],
    });
    req.header('Content-MD5', mapped.contentMD5);
    req.query('cors', mapped.cors);
    req.text(mapped.body);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * Deletes the cors configuration information set for the bucket.
   *
   * @param cors
   * @param bucket
   * @return Response from the API call
   */
  async cORS1(
    cors: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({
      cors: [cors, string()],
      bucket: [bucket, string()],
    });
    req.query('cors', mapped.cors);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsJson(unknown(), requestOptions);
  }

  /**
   * @param cors
   * @param xAmzContentSha256
   * @param bucket
   * @return Response from the API call
   */
  async cORS2(
    cors: string,
    xAmzContentSha256: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      cors: [cors, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('cors', mapped.cors);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.call(requestOptions);
  }
}
