/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class LocationController extends BaseController {
  /**
   * Returns the region the bucket resides in. You set the bucket's region using the LocationConstraint
   * request parameter in a CreateBucket request. For more information, see CreateBucket.
   *
   * @param location
   * @param xAmzContentSha256
   * @param bucket
   * @return Response from the API call
   */
  async bucketLocation(
    location: string,
    xAmzContentSha256: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      location: [location, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('location', mapped.location);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsXml('LocationConstraint', string(), requestOptions);
  }
}
