/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ListAllMyBucketsResult,
  listAllMyBucketsResultSchema,
} from '../models/listAllMyBucketsResult.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class LockController extends BaseController {
  /**
   * Gets the Object Lock configuration for a bucket. The rule specified in the Object Lock configuration
   * will be applied by default to every new object placed in the specified bucket. For more information,
   * see Locking Objects.
   *
   * @param objectLock
   * @param xAmzContentSha256
   * @return Response from the API call
   */
  async objectLockConfiguration(
    objectLock: string,
    xAmzContentSha256: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListAllMyBucketsResult>> {
    const req = this.createRequest('GET', '/');
    const mapped = req.prepareArgs({
      objectLock: [objectLock, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('object-lock', mapped.objectLock);
    return req.callAsXml(
      'ListAllMyBucketsResult',
      listAllMyBucketsResultSchema,
      requestOptions
    );
  }

  /**
   * Gets the Object Lock configuration for a bucket. The rule specified in the Object Lock configuration
   * will be applied by default to every new object placed in the specified bucket. For more information,
   * see Locking Objects.
   *
   * @param objectLock
   * @param xAmzContentSha256
   * @return Response from the API call
   */
  async objectLockConfigurationCopy(
    objectLock: string,
    xAmzContentSha256: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListAllMyBucketsResult>> {
    const req = this.createRequest('PUT', '/');
    const mapped = req.prepareArgs({
      objectLock: [objectLock, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('object-lock', mapped.objectLock);
    return req.callAsXml(
      'ListAllMyBucketsResult',
      listAllMyBucketsResultSchema,
      requestOptions
    );
  }
}
