/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class MiscController extends BaseController {
  /**
   * @param xAmzContentSha256
   * @return Response from the API call
   */
  async root(
    xAmzContentSha256: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/kinlane-productions/');
    const mapped = req.prepareArgs({
      xAmzContentSha256: [xAmzContentSha256, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    return req.call(requestOptions);
  }
}
