/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class NotificationsController extends BaseController {
  /**
   * Returns the notification configuration of a bucket.
   *
   * @param notification
   * @param xAmzContentSha256
   * @param bucket
   * @return Response from the API call
   */
  async bucketNotificationCOnfiguration(
    notification: string,
    xAmzContentSha256: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      notification: [notification, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('notification', mapped.notification);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.call(requestOptions);
  }

  /**
   * Enables notifications of specified events for a bucket. For more information about event
   * notifications, see Configuring Event Notifications.
   *
   * @param notification
   * @param body
   * @param bucket
   * @return Response from the API call
   */
  async bucketNotificationCOnfiguration1(
    notification: string,
    body: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      notification: [notification, string()],
      body: [body, string()],
      bucket: [bucket, string()],
    });
    req.query('notification', mapped.notification);
    req.text(mapped.body);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.call(requestOptions);
  }
}
