/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class RetentionController extends BaseController {
  /**
   * Retrieves an object's retention settings. For more information, see Locking Objects.
   *
   * @param retention
   * @param xAmzContentSha256
   * @param bucket
   * @param key
   * @return Response from the API call
   */
  async retention(
    retention: string,
    xAmzContentSha256: string,
    bucket: string,
    key: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      retention: [retention, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
      key: [key, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('retention', mapped.retention);
    req.appendTemplatePath`/${mapped.bucket}/${mapped.key}`;
    return req.call(requestOptions);
  }

  /**
   * Retrieves an object's retention settings. For more information, see Locking Objects.
   *
   * @param retention
   * @param xAmzContentSha256
   * @param bucket
   * @param key
   * @return Response from the API call
   */
  async retention1(
    retention: string,
    xAmzContentSha256: string,
    bucket: string,
    key: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      retention: [retention, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
      key: [key, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('retention', mapped.retention);
    req.appendTemplatePath`/${mapped.bucket}/${mapped.key}`;
    return req.call(requestOptions);
  }
}
