/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class TorrentController extends BaseController {
  /**
   * Return torrent files from a bucket. BitTorrent can save you bandwidth when you're distributing large
   * files. For more information about BitTorrent, see Amazon S3 Torrent.
   *
   * @param torrent
   * @param xAmzContentSha256
   * @param bucket
   * @param key
   * @return Response from the API call
   */
  async objectTorrent(
    torrent: string,
    xAmzContentSha256: string,
    bucket: string,
    key: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      torrent: [torrent, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
      key: [key, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('torrent', mapped.torrent);
    req.appendTemplatePath`/${mapped.bucket}/${mapped.key}`;
    return req.call(requestOptions);
  }
}
