/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { string, unknown } from '../schema.js';
import { BaseController } from './baseController.js';

export class VersioningController extends BaseController {
  /**
   * Returns the versioning state of a bucket.
   *
   * @param versioning
   * @param xAmzContentSha256
   * @param bucket
   * @return Response from the API call
   */
  async bucketVersioning(
    versioning: string,
    xAmzContentSha256: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<string>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      versioning: [versioning, string()],
      xAmzContentSha256: [xAmzContentSha256, string()],
      bucket: [bucket, string()],
    });
    req.header('x-amz-content-sha256', mapped.xAmzContentSha256);
    req.query('versioning', mapped.versioning);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsText(requestOptions);
  }

  /**
   * Sets the versioning state of an existing bucket. To set the versioning state, you must be the bucket
   * owner.
   *
   * @param versioning
   * @param contentMD5
   * @param body
   * @param bucket
   * @return Response from the API call
   */
  async bucketVersioning1(
    versioning: string,
    contentMD5: string,
    body: string,
    bucket: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown>> {
    const req = this.createRequest('PUT');
    const mapped = req.prepareArgs({
      versioning: [versioning, string()],
      contentMD5: [contentMD5, string()],
      body: [body, string()],
      bucket: [bucket, string()],
    });
    req.header('Content-MD5', mapped.contentMD5);
    req.query('versioning', mapped.versioning);
    req.text(mapped.body);
    req.appendTemplatePath`/${mapped.bucket}`;
    return req.callAsJson(unknown(), requestOptions);
  }
}
