/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for AccessControlPolicy1 type.
 */
public class AccessControlPolicy1 {
    private Owner owner;
    private AccessControlList1 accessControlList;

    /**
     * Default constructor.
     */
    public AccessControlPolicy1() {
    }

    /**
     * Initialization constructor.
     * @param  owner  Owner value for owner.
     * @param  accessControlList  AccessControlList1 value for accessControlList.
     */
    public AccessControlPolicy1(
            Owner owner,
            AccessControlList1 accessControlList) {
        this.owner = owner;
        this.accessControlList = accessControlList;
    }

    /**
     * Getter for Owner.
     * @return Returns the Owner
     */
    @JsonGetter("Owner")
    @XmlElement(name = "Owner")
    public Owner getOwner() {
        return owner;
    }

    /**
     * Setter for Owner.
     * @param owner Value for Owner
     */
    @JsonSetter("Owner")
    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    /**
     * Getter for AccessControlList.
     * @return Returns the AccessControlList1
     */
    @JsonGetter("AccessControlList")
    @XmlElement(name = "AccessControlList")
    public AccessControlList1 getAccessControlList() {
        return accessControlList;
    }

    /**
     * Setter for AccessControlList.
     * @param accessControlList Value for AccessControlList1
     */
    @JsonSetter("AccessControlList")
    public void setAccessControlList(AccessControlList1 accessControlList) {
        this.accessControlList = accessControlList;
    }

    /**
     * Converts this AccessControlPolicy1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccessControlPolicy1 [" + "owner=" + owner + ", accessControlList="
                + accessControlList + "]";
    }

    /**
     * Builds a new {@link AccessControlPolicy1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccessControlPolicy1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(owner, accessControlList);
        return builder;
    }

    /**
     * Class to build instances of {@link AccessControlPolicy1}.
     */
    public static class Builder {
        private Owner owner;
        private AccessControlList1 accessControlList;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  owner  Owner value for owner.
         * @param  accessControlList  AccessControlList1 value for accessControlList.
         */
        public Builder(Owner owner, AccessControlList1 accessControlList) {
            this.owner = owner;
            this.accessControlList = accessControlList;
        }

        /**
         * Setter for owner.
         * @param  owner  Owner value for owner.
         * @return Builder
         */
        public Builder owner(Owner owner) {
            this.owner = owner;
            return this;
        }

        /**
         * Setter for accessControlList.
         * @param  accessControlList  AccessControlList1 value for accessControlList.
         * @return Builder
         */
        public Builder accessControlList(AccessControlList1 accessControlList) {
            this.accessControlList = accessControlList;
            return this;
        }

        /**
         * Builds a new {@link AccessControlPolicy1} object using the set fields.
         * @return {@link AccessControlPolicy1}
         */
        public AccessControlPolicy1 build() {
            return new AccessControlPolicy1(owner, accessControlList);
        }
    }
}
