/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for AccessControlPolicy type.
 */
public class AccessControlPolicy {
    private Owner owner;
    private AccessControlList accessControlList;

    /**
     * Default constructor.
     */
    public AccessControlPolicy() {
    }

    /**
     * Initialization constructor.
     * @param  owner  Owner value for owner.
     * @param  accessControlList  AccessControlList value for accessControlList.
     */
    public AccessControlPolicy(
            Owner owner,
            AccessControlList accessControlList) {
        this.owner = owner;
        this.accessControlList = accessControlList;
    }

    /**
     * Getter for Owner.
     * @return Returns the Owner
     */
    @JsonGetter("Owner")
    @XmlElement(name = "Owner")
    public Owner getOwner() {
        return owner;
    }

    /**
     * Setter for Owner.
     * @param owner Value for Owner
     */
    @JsonSetter("Owner")
    public void setOwner(Owner owner) {
        this.owner = owner;
    }

    /**
     * Getter for AccessControlList.
     * @return Returns the AccessControlList
     */
    @JsonGetter("AccessControlList")
    @XmlElement(name = "AccessControlList")
    public AccessControlList getAccessControlList() {
        return accessControlList;
    }

    /**
     * Setter for AccessControlList.
     * @param accessControlList Value for AccessControlList
     */
    @JsonSetter("AccessControlList")
    public void setAccessControlList(AccessControlList accessControlList) {
        this.accessControlList = accessControlList;
    }

    /**
     * Converts this AccessControlPolicy into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccessControlPolicy [" + "owner=" + owner + ", accessControlList="
                + accessControlList + "]";
    }

    /**
     * Builds a new {@link AccessControlPolicy.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccessControlPolicy.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(owner, accessControlList);
        return builder;
    }

    /**
     * Class to build instances of {@link AccessControlPolicy}.
     */
    public static class Builder {
        private Owner owner;
        private AccessControlList accessControlList;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  owner  Owner value for owner.
         * @param  accessControlList  AccessControlList value for accessControlList.
         */
        public Builder(Owner owner, AccessControlList accessControlList) {
            this.owner = owner;
            this.accessControlList = accessControlList;
        }

        /**
         * Setter for owner.
         * @param  owner  Owner value for owner.
         * @return Builder
         */
        public Builder owner(Owner owner) {
            this.owner = owner;
            return this;
        }

        /**
         * Setter for accessControlList.
         * @param  accessControlList  AccessControlList value for accessControlList.
         * @return Builder
         */
        public Builder accessControlList(AccessControlList accessControlList) {
            this.accessControlList = accessControlList;
            return this;
        }

        /**
         * Builds a new {@link AccessControlPolicy} object using the set fields.
         * @return {@link AccessControlPolicy}
         */
        public AccessControlPolicy build() {
            return new AccessControlPolicy(owner, accessControlList);
        }
    }
}
