/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for AccessControlList1 type.
 */
public class AccessControlList1 {
    private Grant1 grant;

    /**
     * Default constructor.
     */
    public AccessControlList1() {
    }

    /**
     * Initialization constructor.
     * @param  grant  Grant1 value for grant.
     */
    public AccessControlList1(
            Grant1 grant) {
        this.grant = grant;
    }

    /**
     * Getter for Grant.
     * @return Returns the Grant1
     */
    @JsonGetter("Grant")
    @XmlElement(name = "Grant")
    public Grant1 getGrant() {
        return grant;
    }

    /**
     * Setter for Grant.
     * @param grant Value for Grant1
     */
    @JsonSetter("Grant")
    public void setGrant(Grant1 grant) {
        this.grant = grant;
    }

    /**
     * Converts this AccessControlList1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccessControlList1 [" + "grant=" + grant + "]";
    }

    /**
     * Builds a new {@link AccessControlList1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccessControlList1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(grant);
        return builder;
    }

    /**
     * Class to build instances of {@link AccessControlList1}.
     */
    public static class Builder {
        private Grant1 grant;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  grant  Grant1 value for grant.
         */
        public Builder(Grant1 grant) {
            this.grant = grant;
        }

        /**
         * Setter for grant.
         * @param  grant  Grant1 value for grant.
         * @return Builder
         */
        public Builder grant(Grant1 grant) {
            this.grant = grant;
            return this;
        }

        /**
         * Builds a new {@link AccessControlList1} object using the set fields.
         * @return {@link AccessControlList1}
         */
        public AccessControlList1 build() {
            return new AccessControlList1(grant);
        }
    }
}
