/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for AccessControlList type.
 */
public class AccessControlList {
    private List<Grant> grant;

    /**
     * Default constructor.
     */
    public AccessControlList() {
    }

    /**
     * Initialization constructor.
     * @param  grant  List of Grant value for grant.
     */
    public AccessControlList(
            List<Grant> grant) {
        this.grant = grant;
    }

    /**
     * Getter for Grant.
     * @return Returns the List of Grant
     */
    @JsonGetter("Grant")
    @XmlElement(name = "Grant")
    public List<Grant> getGrant() {
        return grant;
    }

    /**
     * Setter for Grant.
     * @param grant Value for List of Grant
     */
    @JsonSetter("Grant")
    public void setGrant(List<Grant> grant) {
        this.grant = grant;
    }

    /**
     * Converts this AccessControlList into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccessControlList [" + "grant=" + grant + "]";
    }

    /**
     * Builds a new {@link AccessControlList.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccessControlList.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(grant);
        return builder;
    }

    /**
     * Class to build instances of {@link AccessControlList}.
     */
    public static class Builder {
        private List<Grant> grant;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  grant  List of Grant value for grant.
         */
        public Builder(List<Grant> grant) {
            this.grant = grant;
        }

        /**
         * Setter for grant.
         * @param  grant  List of Grant value for grant.
         * @return Builder
         */
        public Builder grant(List<Grant> grant) {
            this.grant = grant;
            return this;
        }

        /**
         * Builds a new {@link AccessControlList} object using the set fields.
         * @return {@link AccessControlList}
         */
        public AccessControlList build() {
            return new AccessControlList(grant);
        }
    }
}
