/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for ArnLike type.
 */
public class ArnLike {
    private String awsSourceArn;

    /**
     * Default constructor.
     */
    public ArnLike() {
    }

    /**
     * Initialization constructor.
     * @param  awsSourceArn  String value for awsSourceArn.
     */
    public ArnLike(
            String awsSourceArn) {
        this.awsSourceArn = awsSourceArn;
    }

    /**
     * Getter for AwsSourceArn.
     * @return Returns the String
     */
    @JsonGetter("aws:SourceArn")
    @XmlElement(name = "aws:SourceArn")
    public String getAwsSourceArn() {
        return awsSourceArn;
    }

    /**
     * Setter for AwsSourceArn.
     * @param awsSourceArn Value for String
     */
    @JsonSetter("aws:SourceArn")
    public void setAwsSourceArn(String awsSourceArn) {
        this.awsSourceArn = awsSourceArn;
    }

    /**
     * Converts this ArnLike into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ArnLike [" + "awsSourceArn=" + awsSourceArn + "]";
    }

    /**
     * Builds a new {@link ArnLike.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ArnLike.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(awsSourceArn);
        return builder;
    }

    /**
     * Class to build instances of {@link ArnLike}.
     */
    public static class Builder {
        private String awsSourceArn;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  awsSourceArn  String value for awsSourceArn.
         */
        public Builder(String awsSourceArn) {
            this.awsSourceArn = awsSourceArn;
        }

        /**
         * Setter for awsSourceArn.
         * @param  awsSourceArn  String value for awsSourceArn.
         * @return Builder
         */
        public Builder awsSourceArn(String awsSourceArn) {
            this.awsSourceArn = awsSourceArn;
            return this;
        }

        /**
         * Builds a new {@link ArnLike} object using the set fields.
         * @return {@link ArnLike}
         */
        public ArnLike build() {
            return new ArnLike(awsSourceArn);
        }
    }
}
