/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Bucket type.
 */
public class Bucket {
    private String name;
    private String creationDate;

    /**
     * Default constructor.
     */
    public Bucket() {
    }

    /**
     * Initialization constructor.
     * @param  name  String value for name.
     * @param  creationDate  String value for creationDate.
     */
    public Bucket(
            String name,
            String creationDate) {
        this.name = name;
        this.creationDate = creationDate;
    }

    /**
     * Getter for Name.
     * @return Returns the String
     */
    @JsonGetter("Name")
    @XmlElement(name = "Name")
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * @param name Value for String
     */
    @JsonSetter("Name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for CreationDate.
     * @return Returns the String
     */
    @JsonGetter("CreationDate")
    @XmlElement(name = "CreationDate")
    public String getCreationDate() {
        return creationDate;
    }

    /**
     * Setter for CreationDate.
     * @param creationDate Value for String
     */
    @JsonSetter("CreationDate")
    public void setCreationDate(String creationDate) {
        this.creationDate = creationDate;
    }

    /**
     * Converts this Bucket into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Bucket [" + "name=" + name + ", creationDate=" + creationDate + "]";
    }

    /**
     * Builds a new {@link Bucket.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Bucket.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(name, creationDate);
        return builder;
    }

    /**
     * Class to build instances of {@link Bucket}.
     */
    public static class Builder {
        private String name;
        private String creationDate;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  name  String value for name.
         * @param  creationDate  String value for creationDate.
         */
        public Builder(String name, String creationDate) {
            this.name = name;
            this.creationDate = creationDate;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for creationDate.
         * @param  creationDate  String value for creationDate.
         * @return Builder
         */
        public Builder creationDate(String creationDate) {
            this.creationDate = creationDate;
            return this;
        }

        /**
         * Builds a new {@link Bucket} object using the set fields.
         * @return {@link Bucket}
         */
        public Bucket build() {
            return new Bucket(name, creationDate);
        }
    }
}
