/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Buckets type.
 */
public class Buckets {
    private Bucket bucket;

    /**
     * Default constructor.
     */
    public Buckets() {
    }

    /**
     * Initialization constructor.
     * @param  bucket  Bucket value for bucket.
     */
    public Buckets(
            Bucket bucket) {
        this.bucket = bucket;
    }

    /**
     * Getter for Bucket.
     * @return Returns the Bucket
     */
    @JsonGetter("Bucket")
    @XmlElement(name = "Bucket")
    public Bucket getBucket() {
        return bucket;
    }

    /**
     * Setter for Bucket.
     * @param bucket Value for Bucket
     */
    @JsonSetter("Bucket")
    public void setBucket(Bucket bucket) {
        this.bucket = bucket;
    }

    /**
     * Converts this Buckets into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Buckets [" + "bucket=" + bucket + "]";
    }

    /**
     * Builds a new {@link Buckets.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Buckets.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(bucket);
        return builder;
    }

    /**
     * Class to build instances of {@link Buckets}.
     */
    public static class Builder {
        private Bucket bucket;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  bucket  Bucket value for bucket.
         */
        public Builder(Bucket bucket) {
            this.bucket = bucket;
        }

        /**
         * Setter for bucket.
         * @param  bucket  Bucket value for bucket.
         * @return Builder
         */
        public Builder bucket(Bucket bucket) {
            this.bucket = bucket;
            return this;
        }

        /**
         * Builds a new {@link Buckets} object using the set fields.
         * @return {@link Buckets}
         */
        public Buckets build() {
            return new Buckets(bucket);
        }
    }
}
