/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Condition type.
 */
public class Condition {
    private StringEquals stringEquals;
    private ArnLike arnLike;

    /**
     * Default constructor.
     */
    public Condition() {
    }

    /**
     * Initialization constructor.
     * @param  stringEquals  StringEquals value for stringEquals.
     * @param  arnLike  ArnLike value for arnLike.
     */
    public Condition(
            StringEquals stringEquals,
            ArnLike arnLike) {
        this.stringEquals = stringEquals;
        this.arnLike = arnLike;
    }

    /**
     * Getter for StringEquals.
     * @return Returns the StringEquals
     */
    @JsonGetter("StringEquals")
    @XmlElement(name = "StringEquals")
    public StringEquals getStringEquals() {
        return stringEquals;
    }

    /**
     * Setter for StringEquals.
     * @param stringEquals Value for StringEquals
     */
    @JsonSetter("StringEquals")
    public void setStringEquals(StringEquals stringEquals) {
        this.stringEquals = stringEquals;
    }

    /**
     * Getter for ArnLike.
     * @return Returns the ArnLike
     */
    @JsonGetter("ArnLike")
    @XmlElement(name = "ArnLike")
    public ArnLike getArnLike() {
        return arnLike;
    }

    /**
     * Setter for ArnLike.
     * @param arnLike Value for ArnLike
     */
    @JsonSetter("ArnLike")
    public void setArnLike(ArnLike arnLike) {
        this.arnLike = arnLike;
    }

    /**
     * Converts this Condition into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Condition [" + "stringEquals=" + stringEquals + ", arnLike=" + arnLike + "]";
    }

    /**
     * Builds a new {@link Condition.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Condition.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(stringEquals, arnLike);
        return builder;
    }

    /**
     * Class to build instances of {@link Condition}.
     */
    public static class Builder {
        private StringEquals stringEquals;
        private ArnLike arnLike;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  stringEquals  StringEquals value for stringEquals.
         * @param  arnLike  ArnLike value for arnLike.
         */
        public Builder(StringEquals stringEquals, ArnLike arnLike) {
            this.stringEquals = stringEquals;
            this.arnLike = arnLike;
        }

        /**
         * Setter for stringEquals.
         * @param  stringEquals  StringEquals value for stringEquals.
         * @return Builder
         */
        public Builder stringEquals(StringEquals stringEquals) {
            this.stringEquals = stringEquals;
            return this;
        }

        /**
         * Setter for arnLike.
         * @param  arnLike  ArnLike value for arnLike.
         * @return Builder
         */
        public Builder arnLike(ArnLike arnLike) {
            this.arnLike = arnLike;
            return this;
        }

        /**
         * Builds a new {@link Condition} object using the set fields.
         * @return {@link Condition}
         */
        public Condition build() {
            return new Condition(stringEquals, arnLike);
        }
    }
}
