/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Grantee1 type.
 */
public class Grantee1 {
    private String type;
    private String iD;
    private String displayName;

    /**
     * Default constructor.
     */
    public Grantee1() {
    }

    /**
     * Initialization constructor.
     * @param  type  String value for type.
     * @param  iD  String value for iD.
     * @param  displayName  String value for displayName.
     */
    public Grantee1(
            String type,
            String iD,
            String displayName) {
        this.type = type;
        this.iD = iD;
        this.displayName = displayName;
    }

    /**
     * Getter for Type.
     * @return Returns the String
     */
    @JsonGetter("type")
    @XmlAttribute(name = "type")
    public String getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for String
     */
    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for ID.
     * @return Returns the String
     */
    @JsonGetter("ID")
    @XmlElement(name = "ID")
    public String getID() {
        return iD;
    }

    /**
     * Setter for ID.
     * @param iD Value for String
     */
    @JsonSetter("ID")
    public void setID(String iD) {
        this.iD = iD;
    }

    /**
     * Getter for DisplayName.
     * @return Returns the String
     */
    @JsonGetter("DisplayName")
    @XmlElement(name = "DisplayName")
    public String getDisplayName() {
        return displayName;
    }

    /**
     * Setter for DisplayName.
     * @param displayName Value for String
     */
    @JsonSetter("DisplayName")
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    /**
     * Converts this Grantee1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Grantee1 [" + "type=" + type + ", iD=" + iD + ", displayName=" + displayName + "]";
    }

    /**
     * Builds a new {@link Grantee1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Grantee1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, iD, displayName);
        return builder;
    }

    /**
     * Class to build instances of {@link Grantee1}.
     */
    public static class Builder {
        private String type;
        private String iD;
        private String displayName;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  String value for type.
         * @param  iD  String value for iD.
         * @param  displayName  String value for displayName.
         */
        public Builder(String type, String iD, String displayName) {
            this.type = type;
            this.iD = iD;
            this.displayName = displayName;
        }

        /**
         * Setter for type.
         * @param  type  String value for type.
         * @return Builder
         */
        public Builder type(String type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for iD.
         * @param  iD  String value for iD.
         * @return Builder
         */
        public Builder iD(String iD) {
            this.iD = iD;
            return this;
        }

        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = displayName;
            return this;
        }

        /**
         * Builds a new {@link Grantee1} object using the set fields.
         * @return {@link Grantee1}
         */
        public Grantee1 build() {
            return new Grantee1(type, iD, displayName);
        }
    }
}
