/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for Principal type.
 */
public class Principal {
    private String service;

    /**
     * Default constructor.
     */
    public Principal() {
    }

    /**
     * Initialization constructor.
     * @param  service  String value for service.
     */
    public Principal(
            String service) {
        this.service = service;
    }

    /**
     * Getter for Service.
     * @return Returns the String
     */
    @JsonGetter("Service")
    @XmlElement(name = "Service")
    public String getService() {
        return service;
    }

    /**
     * Setter for Service.
     * @param service Value for String
     */
    @JsonSetter("Service")
    public void setService(String service) {
        this.service = service;
    }

    /**
     * Converts this Principal into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Principal [" + "service=" + service + "]";
    }

    /**
     * Builds a new {@link Principal.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Principal.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(service);
        return builder;
    }

    /**
     * Class to build instances of {@link Principal}.
     */
    public static class Builder {
        private String service;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  service  String value for service.
         */
        public Builder(String service) {
            this.service = service;
        }

        /**
         * Setter for service.
         * @param  service  String value for service.
         * @return Builder
         */
        public Builder service(String service) {
            this.service = service;
            return this;
        }

        /**
         * Builds a new {@link Principal} object using the set fields.
         * @return {@link Principal}
         */
        public Principal build() {
            return new Principal(service);
        }
    }
}
