/*
 * AWSS3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.amazonaws.s3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import javax.xml.bind.annotation.XmlElement;

/**
 * This is a model class for StringEquals type.
 */
public class StringEquals {
    private String awsSourceAccount;
    private String s3XAmzAcl;

    /**
     * Default constructor.
     */
    public StringEquals() {
    }

    /**
     * Initialization constructor.
     * @param  awsSourceAccount  String value for awsSourceAccount.
     * @param  s3XAmzAcl  String value for s3XAmzAcl.
     */
    public StringEquals(
            String awsSourceAccount,
            String s3XAmzAcl) {
        this.awsSourceAccount = awsSourceAccount;
        this.s3XAmzAcl = s3XAmzAcl;
    }

    /**
     * Getter for AwsSourceAccount.
     * @return Returns the String
     */
    @JsonGetter("aws:SourceAccount")
    @XmlElement(name = "aws:SourceAccount")
    public String getAwsSourceAccount() {
        return awsSourceAccount;
    }

    /**
     * Setter for AwsSourceAccount.
     * @param awsSourceAccount Value for String
     */
    @JsonSetter("aws:SourceAccount")
    public void setAwsSourceAccount(String awsSourceAccount) {
        this.awsSourceAccount = awsSourceAccount;
    }

    /**
     * Getter for S3XAmzAcl.
     * @return Returns the String
     */
    @JsonGetter("s3:x-amz-acl")
    @XmlElement(name = "s3:x-amz-acl")
    public String getS3XAmzAcl() {
        return s3XAmzAcl;
    }

    /**
     * Setter for S3XAmzAcl.
     * @param s3XAmzAcl Value for String
     */
    @JsonSetter("s3:x-amz-acl")
    public void setS3XAmzAcl(String s3XAmzAcl) {
        this.s3XAmzAcl = s3XAmzAcl;
    }

    /**
     * Converts this StringEquals into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "StringEquals [" + "awsSourceAccount=" + awsSourceAccount + ", s3XAmzAcl="
                + s3XAmzAcl + "]";
    }

    /**
     * Builds a new {@link StringEquals.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link StringEquals.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(awsSourceAccount, s3XAmzAcl);
        return builder;
    }

    /**
     * Class to build instances of {@link StringEquals}.
     */
    public static class Builder {
        private String awsSourceAccount;
        private String s3XAmzAcl;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  awsSourceAccount  String value for awsSourceAccount.
         * @param  s3XAmzAcl  String value for s3XAmzAcl.
         */
        public Builder(String awsSourceAccount, String s3XAmzAcl) {
            this.awsSourceAccount = awsSourceAccount;
            this.s3XAmzAcl = s3XAmzAcl;
        }

        /**
         * Setter for awsSourceAccount.
         * @param  awsSourceAccount  String value for awsSourceAccount.
         * @return Builder
         */
        public Builder awsSourceAccount(String awsSourceAccount) {
            this.awsSourceAccount = awsSourceAccount;
            return this;
        }

        /**
         * Setter for s3XAmzAcl.
         * @param  s3XAmzAcl  String value for s3XAmzAcl.
         * @return Builder
         */
        public Builder s3XAmzAcl(String s3XAmzAcl) {
            this.s3XAmzAcl = s3XAmzAcl;
            return this;
        }

        /**
         * Builds a new {@link StringEquals} object using the set fields.
         * @return {@link StringEquals}
         */
        public StringEquals build() {
            return new StringEquals(awsSourceAccount, s3XAmzAcl);
        }
    }
}
