/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Grant, grantSchema } from './grant.js';

export interface AccessControlList {
  grant: Grant[];
}

export const accessControlListSchema: Schema<AccessControlList> = object({
  grant: ['Grant', array(lazy(() => grantSchema))],
});
