/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Grant1, grant1Schema } from './grant1.js';

export interface AccessControlList1 {
  grant: Grant1;
}

export const accessControlList1Schema: Schema<AccessControlList1> = object({
  grant: ['Grant', lazy(() => grant1Schema)],
});
