/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import {
  AccessControlList1,
  accessControlList1Schema,
} from './accessControlList1.js';
import { Owner, ownerSchema } from './owner.js';

export interface AccessControlPolicy1 {
  owner: Owner;
  accessControlList: AccessControlList1;
}

export const accessControlPolicy1Schema: Schema<AccessControlPolicy1> = object({
  owner: ['Owner', lazy(() => ownerSchema)],
  accessControlList: [
    'AccessControlList',
    lazy(() => accessControlList1Schema),
  ],
});
