/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Bucket, bucketSchema } from './bucket.js';

export interface Buckets {
  bucket: Bucket;
}

export const bucketsSchema: Schema<Buckets> = object({
  bucket: ['Bucket', lazy(() => bucketSchema)],
});
