/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface Bucket {
  name: string;
  creationDate: string;
}

export const bucketSchema: Schema<Bucket> = object({
  name: ['Name', string()],
  creationDate: ['CreationDate', string()],
});
