/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { ArnLike, arnLikeSchema } from './arnLike.js';
import { StringEquals, stringEqualsSchema } from './stringEquals.js';

export interface Condition {
  stringEquals: StringEquals;
  arnLike: ArnLike;
}

export const conditionSchema: Schema<Condition> = object({
  stringEquals: ['StringEquals', lazy(() => stringEqualsSchema)],
  arnLike: ['ArnLike', lazy(() => arnLikeSchema)],
});
