/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema.js';
import { Owner, ownerSchema } from './owner.js';

export interface Contents {
  key: string;
  lastModified: string;
  eTag: string;
  size: number;
  owner: Owner;
  storageClass: string;
}

export const contentsSchema: Schema<Contents> = object({
  key: ['Key', string()],
  lastModified: ['LastModified', string()],
  eTag: ['ETag', string()],
  size: ['Size', number()],
  owner: ['Owner', lazy(() => ownerSchema)],
  storageClass: ['StorageClass', string()],
});
