/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Grantee1, grantee1Schema } from './grantee1.js';

export interface Grant1 {
  grantee: Grantee1;
  permission: string;
}

export const grant1Schema: Schema<Grant1> = object({
  grantee: ['Grantee', lazy(() => grantee1Schema)],
  permission: ['Permission', string()],
});
