/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Grantee {
  type?: string;
  iD: string;
  displayName: string;
}

export const granteeSchema: Schema<Grantee> = object({
  type: ['type', optional(string()), { isAttr: true }],
  iD: ['ID', string()],
  displayName: ['DisplayName', string()],
});
