/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface Grantee1 {
  type: string;
  iD: string;
  displayName: string;
}

export const grantee1Schema: Schema<Grantee1> = object({
  type: ['type', string(), { isAttr: true }],
  iD: ['ID', string()],
  displayName: ['DisplayName', string()],
});
