/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Grantee, granteeSchema } from './grantee.js';

export interface Grant {
  grantee: Grantee;
  permission: string;
}

export const grantSchema: Schema<Grant> = object({
  grantee: ['Grantee', lazy(() => granteeSchema)],
  permission: ['Permission', string()],
});
