/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema.js';

export interface ListMultipartUploadsResult {
  bucket: string;
  keyMarker: string;
  uploadIdMarker: string;
  nextKeyMarker: string;
  nextUploadIdMarker: string;
  maxUploads: number;
  isTruncated: boolean;
}

export const listMultipartUploadsResultSchema: Schema<ListMultipartUploadsResult> = object(
  {
    bucket: ['Bucket', string()],
    keyMarker: ['KeyMarker', string()],
    uploadIdMarker: ['UploadIdMarker', string()],
    nextKeyMarker: ['NextKeyMarker', string()],
    nextUploadIdMarker: ['NextUploadIdMarker', string()],
    maxUploads: ['MaxUploads', number()],
    isTruncated: ['IsTruncated', boolean()],
  }
);
