/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Buckets, bucketsSchema } from './buckets.js';
import { Owner, ownerSchema } from './owner.js';

export interface ListAllMyBucketsResult {
  owner: Owner;
  buckets: Buckets;
}

export const listAllMyBucketsResultSchema: Schema<ListAllMyBucketsResult> = object(
  {
    owner: ['Owner', lazy(() => ownerSchema)],
    buckets: ['Buckets', lazy(() => bucketsSchema)],
  }
);
