/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema, string } from '../schema.js';

export interface ListBucketResult {
  name: string;
  prefix: string;
  marker: string;
  maxKeys: number;
  isTruncated: boolean;
}

export const listBucketResultSchema: Schema<ListBucketResult> = object({
  name: ['Name', string()],
  prefix: ['Prefix', string()],
  marker: ['Marker', string()],
  maxKeys: ['MaxKeys', number()],
  isTruncated: ['IsTruncated', boolean()],
});
