/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { Contents, contentsSchema } from './contents.js';

export interface ListBucketResult1 {
  name: string;
  prefix: string;
  marker: string;
  maxKeys: number;
  isTruncated: boolean;
  contents: Contents[];
}

export const listBucketResult1Schema: Schema<ListBucketResult1> = object({
  name: ['Name', string()],
  prefix: ['Prefix', string()],
  marker: ['Marker', string()],
  maxKeys: ['MaxKeys', number()],
  isTruncated: ['IsTruncated', boolean()],
  contents: ['Contents', array(lazy(() => contentsSchema))],
});
