/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  object,
  Schema,
  string,
} from '../schema.js';
import { Version, versionSchema } from './version.js';

export interface ListVersionsResult {
  name: string;
  prefix: string;
  keyMarker: string;
  versionIdMarker: string;
  maxKeys: number;
  isTruncated: boolean;
  version: Version[];
}

export const listVersionsResultSchema: Schema<ListVersionsResult> = object({
  name: ['Name', string()],
  prefix: ['Prefix', string()],
  keyMarker: ['KeyMarker', string()],
  versionIdMarker: ['VersionIdMarker', string()],
  maxKeys: ['MaxKeys', number()],
  isTruncated: ['IsTruncated', boolean()],
  version: ['Version', array(lazy(() => versionSchema))],
});
