/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface Owner {
  iD: string;
  displayName: string;
}

export const ownerSchema: Schema<Owner> = object({
  iD: ['ID', string()],
  displayName: ['DisplayName', string()],
});
