/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface Principal {
  service: string;
}

export const principalSchema: Schema<Principal> = object({
  service: ['Service', string()],
});
