/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { Condition, conditionSchema } from './condition.js';
import { Principal, principalSchema } from './principal.js';

export interface Statement {
  sid: string;
  effect: string;
  principal: Principal;
  action: string;
  resource: string;
  condition: Condition;
}

export const statementSchema: Schema<Statement> = object({
  sid: ['Sid', string()],
  effect: ['Effect', string()],
  principal: ['Principal', lazy(() => principalSchema)],
  action: ['Action', string()],
  resource: ['Resource', string()],
  condition: ['Condition', lazy(() => conditionSchema)],
});
