/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface StringEquals {
  awsSourceAccount: string;
  s3XAmzAcl: string;
}

export const stringEqualsSchema: Schema<StringEquals> = object({
  awsSourceAccount: ['aws:SourceAccount', string()],
  s3XAmzAcl: ['s3:x-amz-acl', string()],
});
