/**
 * AWS S3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, number, object, Schema, string } from '../schema.js';
import { Owner, ownerSchema } from './owner.js';

export interface Version {
  key: string;
  versionId: string;
  isLatest: boolean;
  lastModified: string;
  eTag: string;
  size: number;
  owner: Owner;
  storageClass: string;
}

export const versionSchema: Schema<Version> = object({
  key: ['Key', string()],
  versionId: ['VersionId', string()],
  isLatest: ['IsLatest', boolean()],
  lastModified: ['LastModified', string()],
  eTag: ['ETag', string()],
  size: ['Size', number()],
  owner: ['Owner', lazy(() => ownerSchema)],
  storageClass: ['StorageClass', string()],
});
